user = User.create(username: 'username1', password: 'password1')
greeting1 = Greeting.create(text: 'Hello, World!', user_id: 1)
greeting2 = Greeting.create(text: 'Greetings!', user_id: 1)
greeting3 = Greeting.create(text: 'Welcome!', user_id: 1)
greeting4 = Greeting.create(text: 'Hi there!', user_id: 1)
greeting5 = Greeting.create(text: 'Good day!', user_id: 1)
